#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
#

Name:       glog
# >> macros
# << macros

Summary:    Google glog
Version:    0.3.3
Release:    1
Group:      Development/Languages/C++
License:    BSD
URL:        https://github.com/google/glog/
Source:    %{name}-%{version}.tar.gz

BuildRequires:   cmake
BuildRequires:   make
BuildRequires:   automake
Requires:   automake
BuildArch:      noarch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root

%description
Google glog is a library that implements application-level
logging.  This library provides logging APIs based on C++-style
streams and various helper macros.


%prep
%setup -q -n %{name}-%{version}

%define _binaries_in_noarch_packages_terminate_build   0
# >> setup
# << setup

%build

# >> build pre
./configure
make %{?jobs:-j%jobs}
# << build pre



# >> build post
# << build post

%install
mkdir -p $RPM_BUILD_ROOT
make install DESTDIR=$RPM_BUILD_ROOT
# >> install post
# << install post

%pre
# >> pre
# << pre

%preun
# >> preun
# << preun

%files
%defattr(-,root,root,-)
/usr/local/share
/usr/local/include
/usr/local/lib/
/usr/lib/debug

# >> files
# << files
